version: '3'
services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "chulygonoutono2021"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
  chulygon:
    build: .
    ports:
      - "8080:80"